### PR TITLE
Remove PuppetDB dashboard

### LINKED ISSUE #15: Proxy PuppetDB Dashboard does not work with selinux in enforcing mode
It crashes with a 500 error when selinux is enabled in CentOS 7.1.
I need to do some further investigating to determine what may bee needed here.

Not sure exactly where to add selinux rules for this plugin?  In the main foreman selinux?

### LINKED ISSUE #51: can't view puppetdb dashboard inside foreman, as template is missing
hi,

i get following message inside 1.17-rc2 as i try to view the puppetdb-dashboard:
~~~
Missing template puppetdb_foreman/puppetdb/index, application/index with {:locale=>[:de, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rabl]}. 
Searched in: * "/usr/share/foreman/app/views" * "/usr/share/foreman/vendor/ruby/2.3.0/gems/puppetdb_foreman-4.0.0/app/views" * "/usr/share/foreman/vendor/ruby/2.3.0/gems/apipie-rails-0.5.6/app/views" 
~~~

foreman is installed on a deb9 machine.

KR
David

### PR DESCRIPTION
**Pull request by kamils-iRonin**
This closes #51 and closes #15

### CODE REVIEW

**Comment by timogoebel** [comment]
ok to test

File: app/models/setting/puppetdb.rb [hunk 1]
```diff
@@ -27,7 +25,6 @@ def self.default_settings
     [
       set('puppetdb_enabled', _("Integration with PuppetDB, enabled will deactivate a host in PuppetDB when it's deleted in Foreman"), default_enabled),
       set('puppetdb_address', _('Foreman will send PuppetDB requests to this address'), default_address),
-      set('puppetdb_dashboard_address', _('Foreman will proxy PuppetDB Performance Dashboard requests to this address'), default_dashboard_address),
```
Comment (timogoebel) [inline app/models/setting/puppetdb.rb]: We need to remove this with a db migration.

**Comment by timogoebel** [comment]
@kamils-iRonin: Can you rebase?

**Comment by timogoebel** [comment]
[test puppetdb_foreman]

**Comment by timogoebel** [comment]
Thanks, @kamils-iRonin.
